# Project:   ci-test-rust-app
# File:      Makefile
# Purpose:   CI targets wrapping hyperi-ci
#
# License:   Proprietary — HYPERI PTY LIMITED
# Copyright: (c) 2026 HYPERI PTY LIMITED

.PHONY: quality test build

quality:
	hyperi-ci run quality

test:
	hyperi-ci run test

build:
	hyperi-ci run build
