# Project:   HyperI CI
# File:      src/hyperi_ci/container/binary_stage.py
# Purpose:   Stage pre-built binaries into the docker buildx context
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED
"""Stage cross-compiled binaries into the Container stage's build context.

Dockerfiles generated by scalo carry a bare ``COPY <app> <dst>``, while the
Build stage writes ``dist/<app>-linux-<arch>``. One buildx run covers every
platform, so a single context filename cannot hold both arches. The fix is a
rewritten Dockerfile that copies ``dist/<app>-linux-${TARGETARCH}``, which
buildx resolves per platform. Dockerfiles already using that form are left
alone.

The rewrite also gives every ``apt-get`` in the Dockerfile ``-o
Acquire::Retries=5``, so a mirror mid-sync does not fail an arm64 build.

It also appends ``COPY LICENSE /licenses/LICENSE`` (the Red Hat
certification path) when the context root has a licence file, so the image
carries the text its ``org.opencontainers.image.licenses`` label names.
"""

import fnmatch
import posixpath
import re
import tempfile
from pathlib import Path

from hyperi_ci.common import info, warn

LICENCE_DEST = "/licenses/LICENSE"

# Checked in order; the first present wins.
_LICENCE_NAMES = ("LICENSE", "LICENSE.md", "LICENSE.txt")

# Only a bare single-source COPY matches: flags, paths, `$` and multi-source
# forms are never rewritten.
_COPY_LINE = re.compile(
    r"""
    ^(?P<indent>\s*)
    COPY\s+
    (?P<src>[A-Za-z0-9._-]+)
    \s+
    (?P<dst>\S+)
    \s*$
    """,
    re.VERBOSE | re.IGNORECASE,
)

_FROM_LINE = re.compile(r"^\s*FROM\s+(--\S+\s+)*\S+(\s+AS\s+\S+)?\s*$", re.IGNORECASE)

APT_RETRIES = 5

_APT_GET = re.compile(r"\bapt-get(?=\s)")

_ARG_TARGETARCH = re.compile(r"^\s*ARG\s+TARGETARCH\b", re.IGNORECASE)


def stage_binary_dockerfile(
    dockerfile_path: Path,
    *,
    dist_dir: Path | None = None,
    context: Path | None = None,
) -> Path:
    """Return a Dockerfile whose binary COPYs are parameterised by arch.

    Each ``COPY <name> <dst>`` with a ``dist/<name>-linux-<arch>`` artefact
    becomes ``COPY dist/<name>-linux-${TARGETARCH} <dst>``, with ``ARG
    TARGETARCH`` added to its stage. A licence file in ``context`` adds a
    ``COPY <file> /licenses/LICENSE`` to the final stage. The temp file is
    written in the cwd so buildx resolves it against the build context.

    Args:
        dockerfile_path: Path to the project's Dockerfile.
        dist_dir: Where to look for artefacts. Defaults to ``dist``.
        context: Build context searched for a licence file. Defaults to cwd.

    Returns:
        ``dockerfile_path`` when nothing changed, else a new temp Dockerfile
        the caller must ``unlink(missing_ok=True)`` after the build.

    """
    dist = dist_dir or Path("dist")
    original = dockerfile_path.read_text(encoding="utf-8")

    rewrites = _find_binary_copy_rewrites(original, dist)
    licence = find_licence_file(context or Path("."))
    retried = _add_apt_retries(original)
    if not rewrites and licence is None and retried == original:
        return dockerfile_path

    rewritten = retried
    if retried != original:
        info(f"Container: apt-get retries transient fetch errors ({APT_RETRIES}x)")
    if rewrites:
        rewritten = _apply_rewrites(retried, rewrites)
        info(
            f"Container: rewriting {len(rewrites)} bare COPY line(s) to use "
            "${TARGETARCH} for multi-arch builds"
        )
        for src in sorted({r.src for r in rewrites}):
            info(f"  COPY {src} -> COPY dist/{src}-linux-${{TARGETARCH}}")

    if licence is not None:
        rewritten = _append_licence_copy(rewritten, licence)
        info(f"Container: copying {licence} into the image at {LICENCE_DEST}")

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".Dockerfile",
        delete=False,
        dir=".",
        encoding="utf-8",
        newline="\n",
    ) as f:
        f.write(rewritten)
        return Path(f.name)


def _add_apt_retries(content: str) -> str:
    """Return ``content`` with every ``apt-get`` given ``Acquire::Retries``.

    A flag on the command leaves nothing behind in the image and works on
    shell-less or non-apt bases. Comment lines and commands that already set
    ``Acquire::Retries`` are skipped, and no line is added or removed.
    """
    out = []
    for line in content.split("\n"):
        if line.lstrip().startswith("#") or "Acquire::Retries" in line:
            out.append(line)
            continue
        out.append(_APT_GET.sub(f"apt-get -o Acquire::Retries={APT_RETRIES}", line))
    return "\n".join(out)


def find_licence_file(context: Path) -> str | None:
    """Return the licence file name to copy from ``context``, or None.

    The first of ``LICENSE``, ``LICENSE.md``, ``LICENSE.txt`` present at the
    context root wins. If ``.dockerignore`` excludes it, this warns and
    returns None, because a ``COPY`` of it would fail the build.

    Args:
        context: The docker build context directory.

    Returns:
        The file name relative to ``context``, or None.

    """
    for name in _LICENCE_NAMES:
        if not (context / name).is_file():
            continue
        if _dockerignore_excludes(context, name):
            warn(
                f"Container: {name} is excluded by .dockerignore -- the image "
                f"will not carry the licence text. Add !{name} to .dockerignore."
            )
            return None
        return name
    return None


def _dockerignore_excludes(context: Path, name: str) -> bool:
    """Return True if ``context/.dockerignore`` excludes the root-level ``name``.

    Follows Docker's rules for a file at the context root: the last matching
    pattern wins and ``!`` re-includes. A pattern with a directory part can
    only match a root file through a leading ``**/``, which matches zero
    directories.
    """
    ignore_file = context / ".dockerignore"
    if not ignore_file.is_file():
        return False

    excluded = False
    for raw in ignore_file.read_text(encoding="utf-8", errors="replace").splitlines():
        pattern = raw.strip()
        if not pattern or pattern.startswith("#"):
            continue
        negate = pattern.startswith("!")
        if negate:
            pattern = pattern[1:].strip()
        pattern = posixpath.normpath(pattern).lstrip("/")
        while pattern.startswith("**/"):
            pattern = pattern[3:]
        if pattern != "**" and "/" in pattern:
            continue
        # Go's filepath.Match negates a class with `[^`, fnmatch with `[!`.
        pattern = pattern.replace("[^", "[!")
        if pattern == "**" or fnmatch.fnmatchcase(name, pattern):
            excluded = not negate
    return excluded


def _append_licence_copy(content: str, licence: str) -> str:
    """Append a ``COPY <licence> /licenses/LICENSE`` line to the final stage."""
    body = content if content.endswith("\n") or not content else content + "\n"
    return f"{body}COPY {licence} {LICENCE_DEST}\n"


class _CopyRewrite:
    """A COPY line to rewrite: its index, indent, source and destination."""

    __slots__ = ("dst", "indent", "line_index", "src")

    def __init__(
        self,
        line_index: int,
        indent: str,
        src: str,
        dst: str,
    ) -> None:
        self.line_index = line_index
        self.indent = indent
        self.src = src
        self.dst = dst


def _find_binary_copy_rewrites(content: str, dist_dir: Path) -> list[_CopyRewrite]:
    """Return the COPY lines that match a ``dist/<name>-linux-*`` artefact, in order."""
    candidates: list[_CopyRewrite] = []
    for idx, line in enumerate(content.splitlines()):
        match = _COPY_LINE.match(line)
        if not match:
            continue
        src = match.group("src")
        if not _has_dist_artefact(dist_dir, src):
            continue
        candidates.append(
            _CopyRewrite(
                line_index=idx,
                indent=match.group("indent"),
                src=src,
                dst=match.group("dst"),
            )
        )
    return candidates


def _has_dist_artefact(dist_dir: Path, name: str) -> bool:
    """Return True if ``dist/<name>-linux-<arch>`` exists for amd64 or arm64.

    The check stops a bare COPY of an unrelated file, such as a config file,
    from being rewritten.
    """
    if not dist_dir.is_dir():
        return False
    for arch in ("amd64", "arm64"):
        if (dist_dir / f"{name}-linux-{arch}").is_file():
            return True
    return False


def _apply_rewrites(content: str, rewrites: list[_CopyRewrite]) -> str:
    """Return ``content`` with each rewrite applied.

    Each matched COPY becomes ``COPY dist/<src>-linux-${TARGETARCH} <dst>``.
    ``ARG TARGETARCH`` goes immediately before the first rewritten COPY of
    any stage that has not already declared it.
    """
    lines = content.splitlines()
    rewrite_by_index = {r.line_index: r for r in rewrites}

    output: list[str] = []
    in_scope_has_targetarch = False

    for idx, line in enumerate(lines):
        # ARG scope ends at FROM, so each stage needs its own declaration.
        if _FROM_LINE.match(line):
            output.append(line)
            in_scope_has_targetarch = False
            continue

        if _ARG_TARGETARCH.match(line):
            output.append(line)
            in_scope_has_targetarch = True
            continue

        rewrite = rewrite_by_index.get(idx)
        if rewrite is None:
            output.append(line)
            continue

        if not in_scope_has_targetarch:
            output.append(f"{rewrite.indent}ARG TARGETARCH")
            in_scope_has_targetarch = True

        new_line = (
            f"{rewrite.indent}COPY dist/{rewrite.src}-linux-${{TARGETARCH}} "
            f"{rewrite.dst}"
        )
        output.append(new_line)

    trailing = "\n" if content.endswith("\n") else ""
    return "\n".join(output) + trailing
