# Project:   HyperI CI
# File:      src/hyperi_ci/container/binary_stage.py
# Purpose:   Stage pre-built binaries into the docker buildx context
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED
"""Stage cross-compiled binaries into the Container stage's build context.

The Build stage produces ``dist/<app>-linux-<arch>`` artefacts (one per
target). DFE apps' Dockerfiles, generated by `scalo`, use a
bare ``COPY <app> /usr/local/bin/<app>`` line -- which expects a file
literally named ``<app>`` in the build-context root.

For single-arch builds the missing piece is a ``cp dist/<app>-linux-<arch>
<context>/<app>`` step. For multi-arch builds (the common case on
publish dispatch) that doesn't work in a single buildx invocation
because both arches would race for the same context filename.

The clean fix is to rewrite the Dockerfile so the COPY references the
arch-suffixed path with ``${TARGETARCH}`` substitution. buildx sets
TARGETARCH automatically per platform run, both arches succeed in one
invocation, and the ``dist/`` directory is already populated with both
binaries by the upstream Build stage.

Rewriting only fires when the source file is a bare name that matches a
``dist/<name>-linux-*`` artefact. Dockerfiles that already use
``COPY dist/<name>-linux-${TARGETARCH} ...`` (the ci-test-* and
dfe-loader pattern) are left alone.

The same rewrite appends ``COPY LICENSE /licenses/LICENSE`` to the final
stage when the build context root carries a licence file, so every image
ships the licence text its ``org.opencontainers.image.licenses`` label
points at. ``/licenses/`` is the Red Hat container-certification path.
"""

import fnmatch
import posixpath
import re
import tempfile
from pathlib import Path

from hyperi_ci.common import info, warn

LICENCE_DEST = "/licenses/LICENSE"

# Checked in order; the first present wins.
_LICENCE_NAMES = ("LICENSE", "LICENSE.md", "LICENSE.txt")

# A `COPY <src> <dst>` line we might rewrite. Excludes:
#   - flag forms (`COPY --from=...`, `COPY --chown=...`)
#   - paths (anything containing `/`)
#   - already-parameterised paths (containing `$`)
#   - multi-source forms (more than two non-flag args)
_COPY_LINE = re.compile(
    r"""
    ^(?P<indent>\s*)
    COPY\s+
    (?P<src>[A-Za-z0-9._-]+)
    \s+
    (?P<dst>\S+)
    \s*$
    """,
    re.VERBOSE,
)

# Match `FROM <image>` lines -- used to find where to insert ARG TARGETARCH.
# Tolerates `FROM <image> AS <stage>` form.
_FROM_LINE = re.compile(r"^\s*FROM\s+\S+(\s+AS\s+\S+)?\s*$", re.IGNORECASE)

# Match an existing ARG TARGETARCH so we don't insert a duplicate.
_ARG_TARGETARCH = re.compile(r"^\s*ARG\s+TARGETARCH\b", re.IGNORECASE)


def stage_binary_dockerfile(
    dockerfile_path: Path,
    *,
    dist_dir: Path | None = None,
    context: Path | None = None,
) -> Path:
    """Return a path to a Dockerfile with binary COPYs parameterised by arch.

    Reads ``dockerfile_path`` and looks for ``COPY <bare-name> <dst>``
    lines where ``dist/<bare-name>-linux-amd64`` or
    ``dist/<bare-name>-linux-arm64`` exists. Each matching line is
    rewritten to ``COPY dist/<bare-name>-linux-${TARGETARCH} <dst>``
    and ``ARG TARGETARCH`` is inserted in the relevant stage if not
    already present.

    When :func:`find_licence_file` finds a licence file in ``context``, a
    ``COPY <file> /licenses/LICENSE`` line is appended to the final stage.

    If no lines need rewriting and there is no licence file to copy, the
    original ``dockerfile_path`` is returned unchanged -- no temp file is
    created.

    Otherwise, the rewritten content is written to a NamedTemporaryFile
    (in the cwd, so docker buildx can find it relative to the build
    context), and that path is returned. The caller is responsible for
    deleting the temp file when done.

    Args:
        dockerfile_path: Path to the project's Dockerfile.
        dist_dir: Where to look for ``<name>-linux-<arch>`` artefacts.
            Defaults to ``dist/`` relative to cwd.
        context: The docker build context directory, searched for a
            licence file. Defaults to cwd.

    Returns:
        Either ``dockerfile_path`` unchanged (if no rewrite was needed)
        or a Path to a new temp Dockerfile that the caller should
        ``unlink(missing_ok=True)`` after the docker build completes.

    """
    dist = dist_dir or Path("dist")
    original = dockerfile_path.read_text(encoding="utf-8")

    rewrites = _find_binary_copy_rewrites(original, dist)
    licence = find_licence_file(context or Path("."))
    if not rewrites and licence is None:
        return dockerfile_path

    rewritten = original
    if rewrites:
        rewritten = _apply_rewrites(original, rewrites)
        info(
            f"Container: rewriting {len(rewrites)} bare COPY line(s) to use "
            "${TARGETARCH} for multi-arch builds"
        )
        for src in sorted({r.src for r in rewrites}):
            info(f"  COPY {src} -> COPY dist/{src}-linux-${{TARGETARCH}}")

    if licence is not None:
        rewritten = _append_licence_copy(rewritten, licence)
        info(f"Container: copying {licence} into the image at {LICENCE_DEST}")

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".Dockerfile",
        delete=False,
        dir=".",
        encoding="utf-8",
        newline="\n",
    ) as f:
        f.write(rewritten)
        return Path(f.name)


def find_licence_file(context: Path) -> str | None:
    """Return the licence file name to copy from ``context``, or None.

    Looks for ``LICENSE``, then ``LICENSE.md``, then ``LICENSE.txt`` at the
    context root. A file the context's ``.dockerignore`` excludes is skipped
    with a warning, because a ``COPY`` of it would fail the build.

    Args:
        context: The docker build context directory.

    Returns:
        The file name relative to ``context``, or None when there is no
        licence file the build can reach.

    """
    for name in _LICENCE_NAMES:
        if not (context / name).is_file():
            continue
        if _dockerignore_excludes(context, name):
            warn(
                f"Container: {name} is excluded by .dockerignore -- the image "
                f"will not carry the licence text. Add !{name} to .dockerignore."
            )
            return None
        return name
    return None


def _dockerignore_excludes(context: Path, name: str) -> bool:
    """Return True if ``context/.dockerignore`` excludes the root-level ``name``.

    Follows Docker's rules for a file at the context root: the last matching
    pattern wins and ``!`` re-includes. A pattern with a directory part can
    only match a root file through a leading ``**/``, which matches zero
    directories.
    """
    ignore_file = context / ".dockerignore"
    if not ignore_file.is_file():
        return False

    excluded = False
    for raw in ignore_file.read_text(encoding="utf-8", errors="replace").splitlines():
        pattern = raw.strip()
        if not pattern or pattern.startswith("#"):
            continue
        negate = pattern.startswith("!")
        if negate:
            pattern = pattern[1:].strip()
        pattern = posixpath.normpath(pattern).lstrip("/")
        while pattern.startswith("**/"):
            pattern = pattern[3:]
        if pattern != "**" and "/" in pattern:
            continue
        # Go's filepath.Match negates a class with `[^`, fnmatch with `[!`.
        pattern = pattern.replace("[^", "[!")
        if pattern == "**" or fnmatch.fnmatchcase(name, pattern):
            excluded = not negate
    return excluded


def _append_licence_copy(content: str, licence: str) -> str:
    """Append a ``COPY <licence> /licenses/LICENSE`` line to the final stage."""
    body = content if content.endswith("\n") or not content else content + "\n"
    return f"{body}COPY {licence} {LICENCE_DEST}\n"


class _CopyRewrite:
    """A single COPY-line rewrite candidate (line index, original text, src/dst)."""

    __slots__ = ("dst", "indent", "line_index", "src")

    def __init__(
        self,
        line_index: int,
        indent: str,
        src: str,
        dst: str,
    ) -> None:
        self.line_index = line_index
        self.indent = indent
        self.src = src
        self.dst = dst


def _find_binary_copy_rewrites(content: str, dist_dir: Path) -> list[_CopyRewrite]:
    """Scan a Dockerfile for COPY lines that match a dist/<name>-linux-* artefact.

    Returns a list of rewrite candidates in line-order. Empty list means
    "Dockerfile is fine as-is".
    """
    candidates: list[_CopyRewrite] = []
    for idx, line in enumerate(content.splitlines()):
        match = _COPY_LINE.match(line)
        if not match:
            continue
        src = match.group("src")
        if not _has_dist_artefact(dist_dir, src):
            continue
        candidates.append(
            _CopyRewrite(
                line_index=idx,
                indent=match.group("indent"),
                src=src,
                dst=match.group("dst"),
            )
        )
    return candidates


def _has_dist_artefact(dist_dir: Path, name: str) -> bool:
    """Return True if ``dist/<name>-linux-<arch>`` exists for any arch.

    We accept any of the known Linux arches -- buildx's ``TARGETARCH`` is
    set per-platform at build time, so the substitution will resolve to
    whichever the platform run wants. The file existence check is a
    safety net to ensure we don't rewrite a bare COPY that happens to
    share its name with something unrelated (e.g. a config file).
    """
    if not dist_dir.is_dir():
        return False
    for arch in ("amd64", "arm64"):
        if (dist_dir / f"{name}-linux-{arch}").is_file():
            return True
    return False


def _apply_rewrites(content: str, rewrites: list[_CopyRewrite]) -> str:
    """Produce a new Dockerfile with each ``rewrite`` applied.

    Logic:
      1. Replace each matched COPY line with
         ``COPY dist/<src>-linux-${TARGETARCH} <dst>``.
      2. Ensure ``ARG TARGETARCH`` appears after the most-recent FROM
         line preceding each rewritten COPY (and before that COPY).
         Multiple insertions are deduplicated -- one ARG per FROM scope
         even if multiple COPYs are rewritten in the same scope.

    Implemented by walking the file once and emitting lines, tracking
    FROM scope and per-scope ARG-already-inserted state.
    """
    lines = content.splitlines()
    rewrite_by_index = {r.line_index: r for r in rewrites}

    output: list[str] = []
    in_scope_has_targetarch = False

    for idx, line in enumerate(lines):
        # New FROM = new stage = reset TARGETARCH state (ARG doesn't carry
        # across stages in buildx).
        if _FROM_LINE.match(line):
            output.append(line)
            in_scope_has_targetarch = False
            continue

        # Existing ARG TARGETARCH -- note it so we don't insert a duplicate.
        if _ARG_TARGETARCH.match(line):
            output.append(line)
            in_scope_has_targetarch = True
            continue

        rewrite = rewrite_by_index.get(idx)
        if rewrite is None:
            output.append(line)
            continue

        # Need to insert ARG TARGETARCH before the rewritten COPY if not
        # already present in this stage's scope.
        if not in_scope_has_targetarch:
            output.append(f"{rewrite.indent}ARG TARGETARCH")
            in_scope_has_targetarch = True

        new_line = (
            f"{rewrite.indent}COPY dist/{rewrite.src}-linux-${{TARGETARCH}} "
            f"{rewrite.dst}"
        )
        output.append(new_line)

    # Preserve trailing newline if original had one.
    trailing = "\n" if content.endswith("\n") else ""
    return "\n".join(output) + trailing
